package com.simon.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class UserBankDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.export_from_user_bank_id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String exportFromUserBankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.import_to_user_bank_id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String importToUserBankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.transaction_money
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private BigDecimal transactionMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.transaction_date
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private Date transactionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.remark
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.transaction_type
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String transactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.transaction_channel
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String transactionChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank_detail.channel
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.id
     *
     * @return the value of user_bank_detail.id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.id
     *
     * @param id the value for user_bank_detail.id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.export_from_user_bank_id
     *
     * @return the value of user_bank_detail.export_from_user_bank_id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getExportFromUserBankId() {
        return exportFromUserBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.export_from_user_bank_id
     *
     * @param exportFromUserBankId the value for user_bank_detail.export_from_user_bank_id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setExportFromUserBankId(String exportFromUserBankId) {
        this.exportFromUserBankId = exportFromUserBankId == null ? null : exportFromUserBankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.import_to_user_bank_id
     *
     * @return the value of user_bank_detail.import_to_user_bank_id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getImportToUserBankId() {
        return importToUserBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.import_to_user_bank_id
     *
     * @param importToUserBankId the value for user_bank_detail.import_to_user_bank_id
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setImportToUserBankId(String importToUserBankId) {
        this.importToUserBankId = importToUserBankId == null ? null : importToUserBankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.transaction_money
     *
     * @return the value of user_bank_detail.transaction_money
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public BigDecimal getTransactionMoney() {
        return transactionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.transaction_money
     *
     * @param transactionMoney the value for user_bank_detail.transaction_money
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setTransactionMoney(BigDecimal transactionMoney) {
        this.transactionMoney = transactionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.transaction_date
     *
     * @return the value of user_bank_detail.transaction_date
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.transaction_date
     *
     * @param transactionDate the value for user_bank_detail.transaction_date
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.remark
     *
     * @return the value of user_bank_detail.remark
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.remark
     *
     * @param remark the value for user_bank_detail.remark
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.transaction_type
     *
     * @return the value of user_bank_detail.transaction_type
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.transaction_type
     *
     * @param transactionType the value for user_bank_detail.transaction_type
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.transaction_channel
     *
     * @return the value of user_bank_detail.transaction_channel
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getTransactionChannel() {
        return transactionChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.transaction_channel
     *
     * @param transactionChannel the value for user_bank_detail.transaction_channel
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setTransactionChannel(String transactionChannel) {
        this.transactionChannel = transactionChannel == null ? null : transactionChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank_detail.channel
     *
     * @return the value of user_bank_detail.channel
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank_detail.channel
     *
     * @param channel the value for user_bank_detail.channel
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", exportFromUserBankId=").append(exportFromUserBankId);
        sb.append(", importToUserBankId=").append(importToUserBankId);
        sb.append(", transactionMoney=").append(transactionMoney);
        sb.append(", transactionDate=").append(transactionDate);
        sb.append(", remark=").append(remark);
        sb.append(", transactionType=").append(transactionType);
        sb.append(", transactionChannel=").append(transactionChannel);
        sb.append(", channel=").append(channel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBankDetail other = (UserBankDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getExportFromUserBankId() == null ? other.getExportFromUserBankId() == null : this.getExportFromUserBankId().equals(other.getExportFromUserBankId()))
            && (this.getImportToUserBankId() == null ? other.getImportToUserBankId() == null : this.getImportToUserBankId().equals(other.getImportToUserBankId()))
            && (this.getTransactionMoney() == null ? other.getTransactionMoney() == null : this.getTransactionMoney().equals(other.getTransactionMoney()))
            && (this.getTransactionDate() == null ? other.getTransactionDate() == null : this.getTransactionDate().equals(other.getTransactionDate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getTransactionType() == null ? other.getTransactionType() == null : this.getTransactionType().equals(other.getTransactionType()))
            && (this.getTransactionChannel() == null ? other.getTransactionChannel() == null : this.getTransactionChannel().equals(other.getTransactionChannel()))
            && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getExportFromUserBankId() == null) ? 0 : getExportFromUserBankId().hashCode());
        result = prime * result + ((getImportToUserBankId() == null) ? 0 : getImportToUserBankId().hashCode());
        result = prime * result + ((getTransactionMoney() == null) ? 0 : getTransactionMoney().hashCode());
        result = prime * result + ((getTransactionDate() == null) ? 0 : getTransactionDate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getTransactionType() == null) ? 0 : getTransactionType().hashCode());
        result = prime * result + ((getTransactionChannel() == null) ? 0 : getTransactionChannel().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        return result;
    }
}