package com.simon.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class UserBank implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.id
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.user_id
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.bank_type
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private String bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.bank_number
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private String bankNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.bank_name
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.deposit_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private String depositBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.balance
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.id
     *
     * @return the value of user_bank.id
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.id
     *
     * @param id the value for user_bank.id
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.user_id
     *
     * @return the value of user_bank.user_id
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.user_id
     *
     * @param userId the value for user_bank.user_id
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.bank_type
     *
     * @return the value of user_bank.bank_type
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.bank_type
     *
     * @param bankType the value for user_bank.bank_type
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.bank_number
     *
     * @return the value of user_bank.bank_number
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.bank_number
     *
     * @param bankNumber the value for user_bank.bank_number
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.bank_name
     *
     * @return the value of user_bank.bank_name
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.bank_name
     *
     * @param bankName the value for user_bank.bank_name
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.deposit_bank
     *
     * @return the value of user_bank.deposit_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.deposit_bank
     *
     * @param depositBank the value for user_bank.deposit_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank == null ? null : depositBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.balance
     *
     * @return the value of user_bank.balance
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.balance
     *
     * @param balance the value for user_bank.balance
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", bankType=").append(bankType);
        sb.append(", bankNumber=").append(bankNumber);
        sb.append(", bankName=").append(bankName);
        sb.append(", depositBank=").append(depositBank);
        sb.append(", balance=").append(balance);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBank other = (UserBank) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBankType() == null ? other.getBankType() == null : this.getBankType().equals(other.getBankType()))
            && (this.getBankNumber() == null ? other.getBankNumber() == null : this.getBankNumber().equals(other.getBankNumber()))
            && (this.getBankName() == null ? other.getBankName() == null : this.getBankName().equals(other.getBankName()))
            && (this.getDepositBank() == null ? other.getDepositBank() == null : this.getDepositBank().equals(other.getDepositBank()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Sat Jun 26 15:03:03 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBankType() == null) ? 0 : getBankType().hashCode());
        result = prime * result + ((getBankNumber() == null) ? 0 : getBankNumber().hashCode());
        result = prime * result + ((getBankName() == null) ? 0 : getBankName().hashCode());
        result = prime * result + ((getDepositBank() == null) ? 0 : getDepositBank().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        return result;
    }
}