package com.simon.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserBankDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public UserBankDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("`id` like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("`id` not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdIsNull() {
            addCriterion("`export_from_user_bank_id` is null");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdIsNotNull() {
            addCriterion("`export_from_user_bank_id` is not null");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdEqualTo(String value) {
            addCriterion("`export_from_user_bank_id` =", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdNotEqualTo(String value) {
            addCriterion("`export_from_user_bank_id` <>", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdGreaterThan(String value) {
            addCriterion("`export_from_user_bank_id` >", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("`export_from_user_bank_id` >=", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdLessThan(String value) {
            addCriterion("`export_from_user_bank_id` <", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdLessThanOrEqualTo(String value) {
            addCriterion("`export_from_user_bank_id` <=", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdLike(String value) {
            addCriterion("`export_from_user_bank_id` like", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdNotLike(String value) {
            addCriterion("`export_from_user_bank_id` not like", value, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdIn(List<String> values) {
            addCriterion("`export_from_user_bank_id` in", values, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdNotIn(List<String> values) {
            addCriterion("`export_from_user_bank_id` not in", values, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdBetween(String value1, String value2) {
            addCriterion("`export_from_user_bank_id` between", value1, value2, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andExportFromUserBankIdNotBetween(String value1, String value2) {
            addCriterion("`export_from_user_bank_id` not between", value1, value2, "exportFromUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdIsNull() {
            addCriterion("`import_to_user_bank_id` is null");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdIsNotNull() {
            addCriterion("`import_to_user_bank_id` is not null");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdEqualTo(String value) {
            addCriterion("`import_to_user_bank_id` =", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdNotEqualTo(String value) {
            addCriterion("`import_to_user_bank_id` <>", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdGreaterThan(String value) {
            addCriterion("`import_to_user_bank_id` >", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("`import_to_user_bank_id` >=", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdLessThan(String value) {
            addCriterion("`import_to_user_bank_id` <", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdLessThanOrEqualTo(String value) {
            addCriterion("`import_to_user_bank_id` <=", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdLike(String value) {
            addCriterion("`import_to_user_bank_id` like", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdNotLike(String value) {
            addCriterion("`import_to_user_bank_id` not like", value, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdIn(List<String> values) {
            addCriterion("`import_to_user_bank_id` in", values, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdNotIn(List<String> values) {
            addCriterion("`import_to_user_bank_id` not in", values, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdBetween(String value1, String value2) {
            addCriterion("`import_to_user_bank_id` between", value1, value2, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andImportToUserBankIdNotBetween(String value1, String value2) {
            addCriterion("`import_to_user_bank_id` not between", value1, value2, "importToUserBankId");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyIsNull() {
            addCriterion("`transaction_money` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyIsNotNull() {
            addCriterion("`transaction_money` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyEqualTo(BigDecimal value) {
            addCriterion("`transaction_money` =", value, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyNotEqualTo(BigDecimal value) {
            addCriterion("`transaction_money` <>", value, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyGreaterThan(BigDecimal value) {
            addCriterion("`transaction_money` >", value, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`transaction_money` >=", value, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyLessThan(BigDecimal value) {
            addCriterion("`transaction_money` <", value, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`transaction_money` <=", value, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyIn(List<BigDecimal> values) {
            addCriterion("`transaction_money` in", values, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyNotIn(List<BigDecimal> values) {
            addCriterion("`transaction_money` not in", values, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`transaction_money` between", value1, value2, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`transaction_money` not between", value1, value2, "transactionMoney");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNull() {
            addCriterion("`transaction_date` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNotNull() {
            addCriterion("`transaction_date` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateEqualTo(Date value) {
            addCriterion("`transaction_date` =", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotEqualTo(Date value) {
            addCriterion("`transaction_date` <>", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThan(Date value) {
            addCriterion("`transaction_date` >", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`transaction_date` >=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThan(Date value) {
            addCriterion("`transaction_date` <", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThanOrEqualTo(Date value) {
            addCriterion("`transaction_date` <=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIn(List<Date> values) {
            addCriterion("`transaction_date` in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotIn(List<Date> values) {
            addCriterion("`transaction_date` not in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateBetween(Date value1, Date value2) {
            addCriterion("`transaction_date` between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotBetween(Date value1, Date value2) {
            addCriterion("`transaction_date` not between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNull() {
            addCriterion("`transaction_type` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNotNull() {
            addCriterion("`transaction_type` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeEqualTo(String value) {
            addCriterion("`transaction_type` =", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotEqualTo(String value) {
            addCriterion("`transaction_type` <>", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThan(String value) {
            addCriterion("`transaction_type` >", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`transaction_type` >=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThan(String value) {
            addCriterion("`transaction_type` <", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThanOrEqualTo(String value) {
            addCriterion("`transaction_type` <=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLike(String value) {
            addCriterion("`transaction_type` like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotLike(String value) {
            addCriterion("`transaction_type` not like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIn(List<String> values) {
            addCriterion("`transaction_type` in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotIn(List<String> values) {
            addCriterion("`transaction_type` not in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeBetween(String value1, String value2) {
            addCriterion("`transaction_type` between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotBetween(String value1, String value2) {
            addCriterion("`transaction_type` not between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelIsNull() {
            addCriterion("`transaction_channel` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelIsNotNull() {
            addCriterion("`transaction_channel` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelEqualTo(String value) {
            addCriterion("`transaction_channel` =", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelNotEqualTo(String value) {
            addCriterion("`transaction_channel` <>", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelGreaterThan(String value) {
            addCriterion("`transaction_channel` >", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelGreaterThanOrEqualTo(String value) {
            addCriterion("`transaction_channel` >=", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelLessThan(String value) {
            addCriterion("`transaction_channel` <", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelLessThanOrEqualTo(String value) {
            addCriterion("`transaction_channel` <=", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelLike(String value) {
            addCriterion("`transaction_channel` like", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelNotLike(String value) {
            addCriterion("`transaction_channel` not like", value, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelIn(List<String> values) {
            addCriterion("`transaction_channel` in", values, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelNotIn(List<String> values) {
            addCriterion("`transaction_channel` not in", values, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelBetween(String value1, String value2) {
            addCriterion("`transaction_channel` between", value1, value2, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andTransactionChannelNotBetween(String value1, String value2) {
            addCriterion("`transaction_channel` not between", value1, value2, "transactionChannel");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("`channel` is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("`channel` is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("`channel` =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("`channel` <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("`channel` >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("`channel` >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("`channel` <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("`channel` <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("`channel` like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("`channel` not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("`channel` in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("`channel` not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("`channel` between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("`channel` not between", value1, value2, "channel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_bank_detail
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 26 11:31:21 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 11:31:21 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}