package com.simon.mapper;

import java.util.List;

import com.simon.model.UserBankDetail;
import com.simon.model.UserBankDetailExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserBankDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    long countByExample(UserBankDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int deleteByExample(UserBankDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int insert(UserBankDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int insertSelective(UserBankDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    List<UserBankDetail> selectByExample(UserBankDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    UserBankDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserBankDetail record, @Param("example") UserBankDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int updateByExample(@Param("record") UserBankDetail record, @Param("example") UserBankDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int updateByPrimaryKeySelective(UserBankDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank_detail
     *
     * @mbg.generated Sat Jun 26 09:16:15 CST 2021
     */
    int updateByPrimaryKey(UserBankDetail record);

}