package com.simon.mapper;

import java.util.List;

import com.simon.model.UserBank;
import com.simon.model.UserBankExample;
import org.apache.ibatis.annotations.Param;

public interface UserBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    long countByExample(UserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int deleteByExample(UserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int insert(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int insertSelective(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    List<UserBank> selectByExample(UserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    UserBank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserBank record, @Param("example") UserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int updateByExample(@Param("record") UserBank record, @Param("example") UserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int updateByPrimaryKeySelective(UserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bank
     *
     * @mbg.generated Fri Jun 25 23:15:59 CST 2021
     */
    int updateByPrimaryKey(UserBank record);
}